services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: dpsrv-mailserver
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    env_file:
      - ${DPSRV_HOME}/rc/secrets/mailserver/mailserver.env
      - ${DPSRV_HOME}/local.env
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/latest/config/security/understanding-the-ports/
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    ports:
      - "50025:25"    # SMTP  (explicit TLS => STARTTLS, Authentication is DISABLED => use port 465/587 instead)
      - "50143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "50465:465"  # ESMTP (implicit TLS)
      - "40587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "50993:993"  # IMAP4 (implicit TLS)
    volumes:
      - ${DPSRV_HOME}/rc/secrets/mailserver/config/:/tmp/docker-mailserver/
      - ${DPSRV_HOME}/rc/secrets/rspamd/local.d/:/etc/rspamd/local.d/
      - ${DPSRV_HOME}/rc/secrets/rspamd/override.d/:/etc/rspamd/override.d/
      - ${DPSRV_HOME}/var/mail-state/:/var/mail-state/
      - ${DPSRV_HOME}/var/log/mail/:/var/log/mail/
      - ${DPSRV_HOME}/srv/mail/:/var/mail/
      - ${DPSRV_HOME}/rc/secrets/letsencrypt/:/etc/letsencrypt/:ro
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    stop_grace_period: 1m
    # Uncomment if using `ENABLE_FAIL2BAN=1`:
    # cap_add:
    #   - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
networks:
  default:
    name: dpsrv
    external: true
