apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: dpsrv
  name: mailserver-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  # Uncomment and set your storage class if needed
  # storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: dpsrv
  name: mailserver-state
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: dpsrv
  name: mailserver-logs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  # storageClassName: standard
