apiVersion: v1
kind: Service
metadata:
  namespace: dpsrv
  name: mailserver
  labels:
    app: mailserver
spec:
  type: ClusterIP
  selector:
    app: mailserver
  ports:
    - name: tcp-smtp
      port: 25
      targetPort: 25
      protocol: TCP
    - name: tcp-smtps
      port: 465
      targetPort: 465
      protocol: TCP
    - name: tcp-submission
      port: 587
      targetPort: 587
      protocol: TCP
    - name: tcp-imap
      port: 143
      targetPort: 143
      protocol: TCP
    - name: tcp-imaps
      port: 993
      targetPort: 993
      protocol: TCP
