apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: mail-gateway
  namespace: dpsrv
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 25
      name: smtp
      protocol: TCP
    hosts:
    - "*"
  - port:
      number: 465
      name: smtps
      protocol: TCP
    hosts:
    - "*"
  - port:
      number: 587
      name: submission
      protocol: TCP
    hosts:
    - "*"
  - port:
      number: 143
      name: imap
      protocol: TCP
    hosts:
    - "*"
  - port:
      number: 993
      name: imaps
      protocol: TCP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: mailserver
  namespace: dpsrv
spec:
  hosts:
  - "*"
  gateways:
  - mail-gateway
  tcp:
  - match:
    - port: 25
    route:
    - destination:
        host: mailserver.dpsrv.svc.cluster.local
        port:
          number: 25
  - match:
    - port: 465
    route:
    - destination:
        host: mailserver.dpsrv.svc.cluster.local
        port:
          number: 465
  - match:
    - port: 587
    route:
    - destination:
        host: mailserver.dpsrv.svc.cluster.local
        port:
          number: 587
  - match:
    - port: 143
    route:
    - destination:
        host: mailserver.dpsrv.svc.cluster.local
        port:
          number: 143
  - match:
    - port: 993
    route:
    - destination:
        host: mailserver.dpsrv.svc.cluster.local
        port:
          number: 993
